stages:
  - build
  - test

variables:
  # This will suppress any download for dependencies and plugins or upload messages which would clutter the console log.
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=.m2/repository
    -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true
  # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
  # when running from the command line.
  # `installAtEnd` and `deployAtEnd` are only effective with recent version of the corresponding plugins.
  MAVEN_CLI_OPTS: >-
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    -DinstallAtEnd=true
    -DdeployAtEnd=true  

java-build:
  # select the most appropriate image for your project
  image: maven:3.9.6-eclipse-temurin-17
  stage: build
  tags:
    - linux
  # Cache downloaded dependencies and plugins between builds.
  # The key here separates one cache per branch/tag ($CI_COMMIT_REF_SLUG)
  cache:
    key: "maven-$CI_COMMIT_REF_SLUG"
    paths:
      - .m2/repository
  script:
    - ./mvnw $MAVEN_CLI_OPTS package
  #artifacts:
  #  name: "Maven artifacts from $CI_PROJECT_NAME on $CI_COMMIT_REF_SLUG"
  #  paths:
  #    - "**/target"
include:
  - local: cfp-service-main/.gitlab-ci.yml
#  - local: ctf-ui/.gitlab-ci.yml
#  - local: shared/.gitlab-ci.yml


.test-module:
  stage: test
  script:
   - echo "Testing $MODULE"
   - mvn $MAVEN_CLI_OPTS -pl $MODULE test --also-make

.build-module:
  stage: build
  script:
  - echo "Building $MODULE"
  - mvn -pl $MODULE clean compile --also-make
  artifacts:
    expire_in: 10 min
    paths:
    - "*/target"

# BUILD JOBS
build-server-module:
  extends:
  - .cfp-module
  - .build-module

build-ui-module:
  extends:
  - .ui-module
  - .build-module

build-shared-module:
  extends:
  - .shared-module
  - .build-module

# TEST JOBS
test-server-module:
  extends:
  - .cfp-module
  - .build-module

test-ui-module:
  extends:
    - .ui-module
    - .test-module

test-shared-module:
  extends:
   - .shared-module
   - .test-module